package ai

import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"time"
)

type GeminiRequest struct {
	Contents []GeminiContent `json:"contents"`
}

type GeminiContent struct {
	Role  string       `json:"role,omitempty"`
	Parts []GeminiPart `json:"parts"`
}

type GeminiPart struct {
	Text string `json:"text"`
}

type GeminiResponse struct {
	Candidates []struct {
		Content struct {
			Parts []struct {
				Text string `json:"text"`
			} `json:"parts"`
		} `json:"content"`
	} `json:"candidates"`
	Error *struct {
		Message string `json:"message"`
	} `json:"error,omitempty"`
}

func AskGeminiCopilot(prompt string, sessionContext string) (string, error) {
	apiKey := os.Getenv("GEMINI_API_KEY")
	if apiKey == "" {
		return "", fmt.Errorf("GEMINI_API_KEY environment variable is not configured")
	}

	url := fmt.Sprintf("https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash-lite:generateContent?key=%s", apiKey)

	systemInstruction := "You are Replay AI Copilot, a senior DevOps & Linux terminal expert embedded inside the Replay Session Engine. " +
		"Analyze the provided terminal session context and answer user questions concisely with markdown code blocks where applicable."

	fullPrompt := fmt.Sprintf("%s\n\n[TERMINAL SESSION CONTEXT]:\n%s\n\n[USER QUESTION]:\n%s", systemInstruction, sessionContext, prompt)

	reqBody := GeminiRequest{
		Contents: []GeminiContent{
			{
				Parts: []GeminiPart{
					{Text: fullPrompt},
				},
			},
		},
	}

	jsonBytes, err := json.Marshal(reqBody)
	if err != nil {
		return "", err
	}

	client := &http.Client{Timeout: 15 * time.Second}
	resp, err := client.Post(url, "application/json", bytes.NewBuffer(jsonBytes))
	if err != nil {
		return "", fmt.Errorf("failed calling Gemini API: %w", err)
	}
	defer resp.Body.Close()

	respBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("failed reading Gemini response: %w", err)
	}

	var geminiResp GeminiResponse
	if err := json.Unmarshal(respBytes, &geminiResp); err != nil {
		return "", fmt.Errorf("failed parsing Gemini JSON: %w", err)
	}

	if geminiResp.Error != nil {
		return "", fmt.Errorf("Gemini API error: %s", geminiResp.Error.Message)
	}

	if len(geminiResp.Candidates) > 0 && len(geminiResp.Candidates[0].Content.Parts) > 0 {
		return geminiResp.Candidates[0].Content.Parts[0].Text, nil
	}

	return "", fmt.Errorf("no response generated by Gemini API")
}

// StreamGeminiCopilot streams tokens in real time from Gemini API over SSE (Server-Sent Events)
func StreamGeminiCopilot(prompt string, sessionContext string, w http.ResponseWriter) error {
	apiKey := os.Getenv("GEMINI_API_KEY")
	if apiKey == "" {
		return fmt.Errorf("GEMINI_API_KEY environment variable is not configured")
	}

	flusher, ok := w.(http.Flusher)
	if !ok {
		return fmt.Errorf("streaming unsupported by client connection")
	}

	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("Connection", "keep-alive")
	w.Header().Set("X-Accel-Buffering", "no")

	url := fmt.Sprintf("https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash-lite:streamGenerateContent?alt=sse&key=%s", apiKey)

	systemInstruction := "You are Replay AI Copilot, a senior DevOps & Linux terminal expert embedded inside the Replay Session Engine. " +
		"Analyze the provided terminal session context and answer user questions concisely with markdown code blocks where applicable."

	fullPrompt := fmt.Sprintf("%s\n\n[TERMINAL SESSION CONTEXT]:\n%s\n\n[USER QUESTION]:\n%s", systemInstruction, sessionContext, prompt)

	reqBody := GeminiRequest{
		Contents: []GeminiContent{
			{
				Parts: []GeminiPart{
					{Text: fullPrompt},
				},
			},
		},
	}

	jsonBytes, err := json.Marshal(reqBody)
	if err != nil {
		return err
	}

	client := &http.Client{Timeout: 60 * time.Second}
	resp, err := client.Post(url, "application/json", bytes.NewBuffer(jsonBytes))
	if err != nil {
		return fmt.Errorf("failed connecting to Gemini streaming endpoint: %w", err)
	}
	defer resp.Body.Close()

	reader := bufio.NewReader(resp.Body)

	for {
		line, err := reader.ReadString('\n')
		if err != nil {
			if err == io.EOF {
				break
			}
			break
		}

		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "data: ") {
			continue
		}

		rawJSON := strings.TrimPrefix(line, "data: ")
		if rawJSON == "[DONE]" {
			break
		}

		var geminiChunk GeminiResponse
		if err := json.Unmarshal([]byte(rawJSON), &geminiChunk); err != nil {
			continue
		}

		if geminiChunk.Error != nil {
			errPayload, _ := json.Marshal(map[string]string{"token": fmt.Sprintf("\n⚠️ Gemini API Error: %s", geminiChunk.Error.Message)})
			fmt.Fprintf(w, "data: %s\n\n", errPayload)
			flusher.Flush()
			break
		}

		if len(geminiChunk.Candidates) > 0 && len(geminiChunk.Candidates[0].Content.Parts) > 0 {
			token := geminiChunk.Candidates[0].Content.Parts[0].Text
			if token != "" {
				chunkPayload, _ := json.Marshal(map[string]string{"token": token})
				fmt.Fprintf(w, "data: %s\n\n", chunkPayload)
				flusher.Flush()
			}
		}
	}

	fmt.Fprintf(w, "data: [DONE]\n\n")
	flusher.Flush()
	return nil
}
